apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-logging
data:
  fluent.conf: |-
    ################################################################
    # This source gets all logs from local docker host
    @include pods-fluent.conf
    @include elastic-fluent.conf
  pods-fluent.conf: |-
    <source>
      @type tail
      format json
      @log_level warn
      read_from_head true
      tag kubernetes.*
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      exclude_path ["/var/log/containers/fluent*", "/var/log/containers/calico-node*"]
      <parse>
        @type kubernetes
        @type "#{ENV['FLUENT_CONTAINER_TAIL_PARSER_TYPE'] || 'json'}"
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <source>
      @type sample
      sample {"level":"WARN","message":"Rule calculation failed ## HashMap(calculationId -> 5edfb6cc350000da3a78bd6c, questionGroupVersionId -> 6070798c43000090e864cbd6, questionGroupId -> 5abd4cdc2100008200f29154, supplierId -> 4b1da344504943aec681d09c, siteId -> 5ed7e72328000035b3add918)","env":"time","AVETTA_ENV":"time","environment":"time","appName":"recalcservice","service.name":"recalcservice","serviceName":"recalcservice","exception":null,"position":"com.avetta.recalcservice.services.calculations.DefaultRuleService#runRule evaluateResult:31","thread_name":"scala-execution-context-global-23","timestamp":"2022-01-08T07:49:26"}
      tag sample
    </source>

    <filter **>
      @type record_transformer
      <record>
        AVETTA_ENV "#{ENV['AVETTA_ENV']}"
      </record>
    </filter>

    <filter kubernetes.**>
      @type kubernetes_metadata
      @id filter_kube_metadata
      kubernetes_url "#{ENV['FLUENT_FILTER_KUBERNETES_URL'] || 'https://' + ENV.fetch('KUBERNETES_SERVICE_HOST') + ':' + ENV.fetch('KUBERNETES_SERVICE_PORT') + '/api'}"
      verify_ssl "#{ENV['KUBERNETES_VERIFY_SSL'] || true}"
      ca_file "#{ENV['KUBERNETES_CA_FILE']}"
      skip_labels "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_LABELS'] || 'false'}"
      skip_container_metadata "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_CONTAINER_METADATA'] || 'false'}"
      skip_master_url "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_MASTER_URL'] || 'false'}"
      skip_namespace_metadata "#{ENV['FLUENT_KUBERNETES_METADATA_SKIP_NAMESPACE_METADATA'] || 'false'}"
    </filter>

    <filter kubernetes.**>
      @type parser
      key_name log
      <parse>
        @type multi_format
        <pattern>
          format json
        </pattern>
        <pattern>
          format nginx
        </pattern>
        <pattern>
          format apache2
        </pattern>
        <pattern>
          format apache_error
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </filter>
  elastic-fluent.conf: |-
    <match **>
      @type elasticsearch
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST'] || 'elasticsearch.kube-logging.svc.cluster.local'}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT'] || '9200'}"
      type_name fluentd
      logstash_format true
      logstash_dateformat %Y-%m-%d
      logstash_prefix fluentd-k8s
      include_timestamp true
    </match>
